In [1]:
import numpy as np

🌟 Exercice 1 : Création d'un tableau 1D

In [2]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercice 2 : Conversion de type


In [3]:
arr = np.array([3.14, 2.17, 0, 1, 2])

arr = arr.astype(int)

print(arr)

[3 2 0 1 2]


🌟 Exercice 3 : Tableau multidimensionnel 3×3

In [4]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercice 4 : Tableau aléatoire 4×5

In [5]:
arr = np.random.rand(4, 5)

print(arr)

[[0.4638796  0.38570604 0.34887436 0.80722008 0.00256433]
 [0.34703645 0.5133708  0.37771361 0.15069516 0.60139691]
 [0.93558628 0.61283431 0.53619252 0.23786165 0.56537479]
 [0.46248019 0.49725357 0.55649385 0.9850919  0.0490264 ]]


🌟 Exercice 5 : Sélectionner la deuxième ligne

In [6]:
arr = np.array([
    [21,22,23,22,22],
    [20,21,22,23,24],
    [21,22,23,22,22]
])

second_row = arr[1]

print(second_row)

[20 21 22 23 24]


🌟 Exercice 6 : Inverser l'ordre d'un tableau

In [7]:
arr = np.arange(10)

reversed_arr = arr[::-1]

print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


🌟 Exercice 7 : Matrice identité 4×4

In [8]:
identity = np.eye(4)

print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercice 8 : Somme et moyenne

In [9]:
arr = np.arange(10)

print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))

Sum: 45
Average: 4.5


🌟 Exercice 9 : Reshape en matrice 4×5

In [10]:
arr = np.arange(1, 21)

matrix = arr.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercice 10 : Sélection conditionnelle

In [11]:
arr = np.arange(10)

odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)


[1 3 5 7 9]
